export const spaceWidth: number = 100;
export const spaceHeight: number = 100;
export const spaceMargin: number = 15;
// export const boardWidth: number = spaceWidth * boardCols;
// export const boardHeight: number = spaceHeight * boardRows;
// export const spaceColors: GradientColor[] = [pink, green, orange, blue, yellow, brown, darker];
// export const spaceColors: GradientColor[] = ["#D4CBE5", "#FE5D26", "#DD7373", "#EAD94C", "#5C5D67", "#7D83FF", darker];
export const spaceColors: GradientColor[] = ["#885053","#fe5f55","#777da7","#94c9a9","#c6ecae", "#F59CA9", darker];
export const spaceCornerRadius: number = 50;
export const pawnColors: GradientColor[] = ["#9d0000", "#76009d", "#229d00", "#00259d"]
export const pawnRadius: number = spaceWidth / 8;
export const diceWidth: number = 50
export const diceHeight: number = 50;
export const backgroundColor: GradientColor = "#13005A";
export const pipeBackgroundColor: GradientColor = lighter;
export const framePadding: number = 60;
export const questionPanelBackgroundColor: GradientColor = lighter;
export const questionPanelPadding: number = 10;
export const timeBetweenMove: number = 250;
