export const spaceWidth: number = 120;
export const spaceHeight: number = 120;
export const spaceMargin: number = 15;
export const spaceColors: GradientColor[] = ["#885053", "#fe5f55", "#777da7", "#94c9a9", "#c6ecae", "#F59CA9", darker];
export const spaceCornerRadius: number = 50;
export const pawnColors: GradientColor[] = ["#9d0000", "#76009d", "#229d00", "#00259d"]
export const pawnRadius: number = spaceWidth / 8;
export const diceWidth: number = 50
export const diceHeight: number = 50;
export const backgroundColor: GradientColor = "#13005A";
export const pipeBackgroundColor: GradientColor = lighter;
export const framePadding: number = 60;
export const questionPanelBackgroundColor: GradientColor = lighter;
export const questionPanelPadding: number = 10;
export const timeBetweenMove: number = 250;
